<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="3" failed="1" ignored="0" total="4" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="48138" started-at="2022-02-08T10:17:33Z" finished-at="2022-02-08T10:18:21Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="48138" started-at="2022-02-08T10:17:33Z" finished-at="2022-02-08T10:18:21Z">
      <class name="testcase.LanuchBrowser">
        <test-method status="PASS" signature="setup()[pri:0, instance:testcase.LanuchBrowser@59f99ea]" name="setup" is-config="true" duration-ms="164" started-at="2022-02-08T15:47:33Z" finished-at="2022-02-08T15:47:33Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="LunchApplication()[pri:0, instance:testcase.LanuchBrowser@59f99ea]" name="LunchApplication" is-config="true" duration-ms="10202" started-at="2022-02-08T15:47:33Z" finished-at="2022-02-08T15:47:43Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LunchApplication -->
        <test-method status="SKIP" signature="VerifyRetryFailedTc()[pri:0, instance:testcase.LanuchBrowser@59f99ea]" name="VerifyRetryFailedTc" duration-ms="2073" started-at="2022-02-08T15:47:43Z" finished-at="2022-02-08T15:47:45Z">
          <exception class="java.lang.ArithmeticException">
            <message>
              <![CDATA[/ by zero]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.ArithmeticException: / by zero
	at testcase.LanuchBrowser.VerifyRetryFailedTc(LanuchBrowser.java:84)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.ArithmeticException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- VerifyRetryFailedTc -->
        <test-method status="PASS" signature="teardown(org.testng.ITestResult)[pri:0, instance:testcase.LanuchBrowser@59f99ea]" name="teardown" is-config="true" duration-ms="700" started-at="2022-02-08T15:47:45Z" finished-at="2022-02-08T15:47:46Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=VerifyRetryFailedTc status=SKIP method=LanuchBrowser.VerifyRetryFailedTc()[pri:0, instance:testcase.LanuchBrowser@59f99ea] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
        <test-method status="PASS" signature="LunchApplication()[pri:0, instance:testcase.LanuchBrowser@59f99ea]" name="LunchApplication" is-config="true" duration-ms="8731" started-at="2022-02-08T15:47:46Z" finished-at="2022-02-08T15:47:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LunchApplication -->
        <test-method status="SKIP" signature="VerifyRetryFailedTc()[pri:0, instance:testcase.LanuchBrowser@59f99ea]" name="VerifyRetryFailedTc" duration-ms="2044" started-at="2022-02-08T15:47:55Z" finished-at="2022-02-08T15:47:57Z">
          <exception class="java.lang.ArithmeticException">
            <message>
              <![CDATA[/ by zero]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.ArithmeticException: / by zero
	at testcase.LanuchBrowser.VerifyRetryFailedTc(LanuchBrowser.java:84)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:1014)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1215)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.ArithmeticException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- VerifyRetryFailedTc -->
        <test-method status="PASS" signature="teardown(org.testng.ITestResult)[pri:0, instance:testcase.LanuchBrowser@59f99ea]" name="teardown" is-config="true" duration-ms="697" started-at="2022-02-08T15:47:57Z" finished-at="2022-02-08T15:47:58Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=VerifyRetryFailedTc status=SKIP method=LanuchBrowser.VerifyRetryFailedTc()[pri:0, instance:testcase.LanuchBrowser@59f99ea] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
        <test-method status="PASS" signature="LunchApplication()[pri:0, instance:testcase.LanuchBrowser@59f99ea]" name="LunchApplication" is-config="true" duration-ms="8550" started-at="2022-02-08T15:47:58Z" finished-at="2022-02-08T15:48:06Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LunchApplication -->
        <test-method status="SKIP" signature="VerifyRetryFailedTc()[pri:0, instance:testcase.LanuchBrowser@59f99ea]" name="VerifyRetryFailedTc" duration-ms="2039" started-at="2022-02-08T15:48:06Z" finished-at="2022-02-08T15:48:08Z">
          <exception class="java.lang.ArithmeticException">
            <message>
              <![CDATA[/ by zero]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.ArithmeticException: / by zero
	at testcase.LanuchBrowser.VerifyRetryFailedTc(LanuchBrowser.java:84)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:1014)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1215)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.ArithmeticException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- VerifyRetryFailedTc -->
        <test-method status="PASS" signature="teardown(org.testng.ITestResult)[pri:0, instance:testcase.LanuchBrowser@59f99ea]" name="teardown" is-config="true" duration-ms="726" started-at="2022-02-08T15:48:08Z" finished-at="2022-02-08T15:48:09Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=VerifyRetryFailedTc status=SKIP method=LanuchBrowser.VerifyRetryFailedTc()[pri:0, instance:testcase.LanuchBrowser@59f99ea] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
        <test-method status="PASS" signature="LunchApplication()[pri:0, instance:testcase.LanuchBrowser@59f99ea]" name="LunchApplication" is-config="true" duration-ms="8856" started-at="2022-02-08T15:48:09Z" finished-at="2022-02-08T15:48:18Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LunchApplication -->
        <test-method status="FAIL" signature="VerifyRetryFailedTc()[pri:0, instance:testcase.LanuchBrowser@59f99ea]" name="VerifyRetryFailedTc" duration-ms="2038" started-at="2022-02-08T15:48:18Z" finished-at="2022-02-08T15:48:20Z">
          <exception class="java.lang.ArithmeticException">
            <message>
              <![CDATA[/ by zero]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.ArithmeticException: / by zero
	at testcase.LanuchBrowser.VerifyRetryFailedTc(LanuchBrowser.java:84)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:1014)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1215)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.ArithmeticException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- VerifyRetryFailedTc -->
        <test-method status="PASS" signature="teardown(org.testng.ITestResult)[pri:0, instance:testcase.LanuchBrowser@59f99ea]" name="teardown" is-config="true" duration-ms="1451" started-at="2022-02-08T15:48:20Z" finished-at="2022-02-08T15:48:21Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=VerifyRetryFailedTc status=FAILURE method=LanuchBrowser.VerifyRetryFailedTc()[pri:0, instance:testcase.LanuchBrowser@59f99ea] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
        <test-method status="PASS" signature="teardown1()[pri:0, instance:testcase.LanuchBrowser@59f99ea]" name="teardown1" is-config="true" duration-ms="318" started-at="2022-02-08T15:48:21Z" finished-at="2022-02-08T15:48:22Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown1 -->
      </class> <!-- testcase.LanuchBrowser -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
